spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse-management-system
    username: root
  liquibase:
    enabled: true
    contexts: prod
    change-log: db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
