spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate